# Python ve Numpy ile Nümerik (Sayısal) Hesaplama

![](https://i.imgur.com/mg8O3kd.png)


Bu eğitim aşağıdaki konuları kapsar:

- Python'da sayısal verilerle çalışma
- Python listelerinden (lists) Numpy dizilerine (arrays) geçiş
- Çok boyutlu Numpy dizileri ve faydaları
- Dizi işlemleri (operations), yayınlama (broadcasting), indeksleme (indexing) ve dilimleme (slicing)
- Numpy kullanarak CSV veri dosyalarıyla çalışma

## Sayısal Verilerle Çalışma

*Veri Analizi* içindeki "veriler" tipik olarak, hisse senedi fiyatları, satış rakamları, sensör ölçümleri, spor skorları, veritabanı tabloları vb. gibi sayısal verilere atıfta bulunur. [Numpy](https://numpy.org) kütüphanesi, Python'da sayısal hesaplama için özel veri yapıları, fonksiyonlar ve diğer araçlar sağlar. Sayısal verilerle çalışırken Numpy'nin  neden ve nasıl kullanılacağını görmek için bir örnek üzerinde çalışalım.


> Farzedelim ki, bir bölgenin elma yetiştirmek için uygun olup olmadığını belirlemek için sıcaklık, yağış ve nem gibi iklim verilerini kullanmak istiyoruz. Bunu yapmak için lineer bir denklem olarak ortalama sıcaklık (Fahrenheit derece olarak), yağış (milimetre olarak) ve ortalama bağıl nem (yüzde olarak) gibi, elmaların yıllık verimi (hektar başına ton) ile iklim koşulları arasındaki ilişkiyi formüle ederek basit bir yaklaşım yapabiliriz.
>
>  `elmalarin_hasilati = w1 * sicaklik + w2 * yagis + w3 * nem`

Elma verimini sıcaklık, yağış ve nemin ağırlıklı toplamı olarak ifade ediyoruz. Bu denklem bir tahmindir (approximation), çünkü gerçek ilişki doğrusal (lineer) olmayabilir ve başka faktörler içerebilir. Ama bunun gibi basit doğrusal (lineer) bir model pratikte genellikle iyi sonuç verir.

Geçmiş verilerin bazı istatistiksel analizine dayanarak, "w1", "w2" ve "w3" ağırlıkları için makul değerler bulabiliriz. İşte örnek bir değer kümesi:

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

Bir bölge için bazı iklim verileri göz önüne alındığında, artık elma hasılatını tahmin edebiliriz. İşte bazı örnek veriler:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

İlk olarak, bir bölge için iklim verilerini kaydederken bazı değişkenler tanımlayabiliriz.

In [ ]:
kanto_sicaklik = 73
kanto_yagis = 67
kanto_nem = 43

Artık elmaların hasılatını tahmin etmek için bu değişkenleri lineer denklemde yerine koyabiliriz.

In [ ]:
kanto_elmalarin_hasilati = kanto_sicaklik * w1 + kanto_yagis * w2 + kanto_nem * w3

In [ ]:
kanto_elmalarin_hasilati

56.8

In [ ]:
print("Kanto bölgesinde beklenen elma hasılatı hektar başına {} tondur.".format(kanto_elmalarin_hasilati))

Kanto bölgesinde beklenen elma hasılatı hektar başına 56.8 tondur.


Birden fazla bölge için yukarıdaki hesaplamayı yapmayı biraz daha kolaylaştırmak için, her bölge için iklim verilerini bir vektör, yani bir sayı listesi olarak gösterebiliriz.

In [ ]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

Her vektördeki üç sayı sırasıyla sıcaklık, yağış ve nem verilerini temsil eder.

Formülde kullanılan ağırlık kümesini (the set of weights) vektör olarak da gösterebiliriz.

In [ ]:
weights = [w1, w2, w3]

Şimdi, iklim verileri ve ilgili ağırlıklar göz önüne alındığında, elmaların (veya başka herhangi bir mahsulün) verimini hesaplamak için mahsul verimi fonksiyonunu yazabiliriz.

In [ ]:
def mahsul_hasilati(bolge, weights):
    sonuc = 0
    for x, w in zip(bolge, weights):
        sonuc = sonuc + x * w 
    return sonuc

In [ ]:
mahsul_hasilati(kanto, weights)

56.8

In [ ]:
mahsul_hasilati(johto, weights)

76.9

In [ ]:
mahsul_hasilati(unova, weights)

74.9

## Python listelerinden (lists) Numpy dizilerine (arrays) geçiş


`mahsul_hasilati` (iki vektörün eleman bazında çarpımı ve sonuçlarının toplamının alınması) ile gerçekleştirilen hesaplamaya da *nokta çarpım* yani *dot product* denir. Dot product hakkında daha fazla bilgiyi buradan edinebilirsiniz: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length . 

Numpy kütüphanesi, iki vektörün nokta çarpımını (dot productını) hesaplamak için hazır bir fonksiyon sağlar. Ancak, önce listeleri (lists) Numpy dizilerine (arrays) dönüştürmeliyiz.

Şimdi `pip` paket yöneticisini kullanarak Numpy kütüphanesini yükleyelim.

Ardından, `numpy` modülünü içe aktaralım (import edelim). Numpy'ı `np` takma adıyla içe aktarmak yaygın bir uygulamadır.

In [ ]:
import numpy as np

Artık Numpy dizileri (arrays) oluşturmak için `np.array` fonksiyonunu kullanabiliriz.

In [ ]:
kanto = np.array([73, 67, 43])

In [ ]:
kanto

array([73, 67, 43])

In [ ]:
weights = np.array([w1, w2, w3])

In [ ]:
weights

array([0.3, 0.2, 0.5])

Numpy dizileri (arrays) `ndarray` türüne sahiptir.

In [ ]:
type(kanto)

numpy.ndarray

In [ ]:
type(weights)

numpy.ndarray

Tıpkı listeler (lists) gibi, Numpy dizileri (arrays) de [] indeksleme notasyonunu (indexing notation) destekler.

In [ ]:
weights[0]

0.3

In [ ]:
kanto[2]

43

## Numpy dizilerinde (arrays) çalışma

Şimdi `np.dot` fonksiyonunu kullanarak iki vektörün nokta çarpımını (dot productını) hesaplayabiliriz.

In [ ]:
np.dot(unova, weights)

74.9

Numpy dizileri (arrays) tarafından desteklenen düşük seviyeli işlemlerle aynı sonucu elde edebiliriz: eleman bazında çarpma yapmak ve elde edilen sayıların toplamını hesaplamak.

In [ ]:
a = (kanto * weights)
a

array([21.9, 13.4, 21.5])

`*` operatörü, iki dize (array) aynı boyuta sahipse eğer, iki dizinin (array) eleman bazında çarpmasını gerçekleştirir. `sum` yöntemi, bir dizideki (array) sayıların toplamını hesaplar.

In [ ]:
ab = sum(kanto)
ab

183

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
arr1 * arr2

array([ 4, 10, 18])

In [ ]:
arr2.sum()

15

## Numpy dizilerini (arrays) kullanmanın faydaları

Numpy dizileri (arrays), sayısal veriler üzerinde çalışmak için Python listelerine (lists) göre aşağıdaki avantajları sunar:

- **Kullanım kolaylığı**: `urun_mahsulu` gibi döngüler (loops) & özel fonksiyonlar kullanmak yerine `(kanto * weights).sum()` gibi küçük, özlü ve sezgisel matematiksel ifadeler yazabiliriz.

- **Performans**: Numpy işlemleri ve fonksiyonları, çalışma zamanında (runtime) yorumlanan Python ifadelerini (statements) & döngülerini (loops) kullanmaktan çok daha hızlı hale getiren C++'da dahili olarak uygulanır.

Her biri bir milyon elemanlı iki vektör üzerinde Python döngüleri (loops) ile Numpy dizileri (arrays) kullanılarak gerçekleştirilen nokta çarpımlarının (dot product) bir karşılaştırması burada.

In [ ]:
# Python listeleri (lists)
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 220 ms, sys: 0 ns, total: 220 ms
Wall time: 220 ms


In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.76 ms, sys: 0 ns, total: 2.76 ms
Wall time: 2.87 ms


833332333333500000

Gördüğümüz gibi, `np.dot` kullanmak, bir `for` döngüsü kullanmaktan 100 kat daha hızlıdır. Bu, on binlerce veya milyonlarca veri noktası içeren gerçekten büyük veri kümeleriyle çalışırken özellikle Numpy'yi kullanışlı hale getirir.

## Çok boyutlu Numpy dizileri (arrays)

Artık bir adım daha ileri gidebilir ve tek bir 2 boyutlu Numpy dizisi (array) kullanarak tüm bölgeler için iklim verilerini represent edebiliriz.

In [ ]:
iklim_verisi = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [ ]:
iklim_verisi

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

Lisede lineer cebir dersi aldıysanız, yukarıdaki 2 boyutlu diziyi beş satır (rows) ve üç sütunlu (columns) bir matris olarak tanıyabilirsiniz. Her satır bir bölgeyi temsil eder ve sütunlar sırasıyla sıcaklık, yağış ve nemi temsil eder.

Numpy dizileri (arrays) herhangi bir sayıda boyutta olabilir ve her bir boyut boyunca farklı uzunluklara sahip olabilir. Bir dizinin (array) `.shape` özelliğini kullanarak her bir boyut boyunca uzunluğu inceleyebiliriz.


<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">


In [ ]:
# 2D array (matrix)
iklim_verisi.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
# 1D array (vector)
weights.shape

(3,)

In [ ]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])


In [ ]:
arr3.shape

(2, 2, 3)

Numpy dizisindeki (array) tüm öğeler aynı veri türüne sahiptir.

`.dtype` özelliğini kullanarak bir dizinin veri türünü kontrol edebiliriz.

In [ ]:
weights.dtype

dtype('float64')

In [ ]:
iklim_verisi.dtype

dtype('int64')

Bir dizi tek bir floating point number bile içeriyorsa, diğer tüm öğeler de float'a dönüştürülür.

In [ ]:
arr3.dtype

dtype('float64')

Şimdi, `iklim_verisi` (5x3'lük bir matris) ve `weights` (3 uzunluğunda bir vektör) arasında tek bir matris çarpımı kullanarak, tüm bölgelerde elmaların tahmin edilen hasılatlarını hesaplayabiliriz. İşte görsel olarak görüntüsü:


<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

Bu oynatma listesinin ilk 3-4 videosunu izleyerek matrisler ve matris çarpımı hakkında bilgi edinebiliriz: https://www.youtube.com/watch?v=xyAuNHPsq-g&list=PLFD0EB975BA0CC1E0&index=1 

Matris çarpımını yapmak için `np.matmul` fonksiyonunu veya `@` operatörünü kullanabiliriz.

In [ ]:
np.matmul(iklim_verisi, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
iklim_verisi @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## CSV veri dosyalarıyla çalışma

Numpy ayrıca dosyalardan okuma ve dosyalara yazma yardımcı işlevleri sağlar. 10.000 iklim ölçümünü (sıcaklık, yağış ve nem) içeren `climate.txt` dosyasını aşağıdaki formatta indirelim:


```
sicaklik,yagis,nem
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```
Bu veri depolama biçimi, *comma-separated values (virgülle ayrılmış değerler)* veya CSV olarak bilinir.

> **CSVs**: Virgülle ayrılmış değerler (CSV) dosyası, değerleri ayırmak için virgül kullanan sınırlandırılmış bir metin dosyasıdır. Dosyanın her satırı bir veri kaydıdır. Her kayıt, virgülle ayrılmış bir veya daha fazla alandan oluşur. Bir CSV dosyası genellikle tablo verilerini (sayılar ve metin) düz metin olarak depolar; bu durumda her satırda aynı sayıda alan (field, not area) bulunur. (Vikipedi)

Bu dosyayı numpy dizisine okumak için `genfromtxt` fonksiyonunu kullanabiliriz.

In [ ]:
import urllib.request as ur

ur.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f4983195050>)

In [ ]:
iklim_verisi = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [ ]:
iklim_verisi

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
iklim_verisi.shape

(10000, 3)

Şimdi, belirli bir weight kümesini kullanarak bütün veri kümesi için elma hasılatını tahmin etmek için `@` operatörünü kullanarak bir matris çarpımı yapabiliriz.

In [ ]:
weights = np.array([0.3, 0.2, 0.5])

In [ ]:
hasilatlar = iklim_verisi @ weights      

In [ ]:
hasilatlar

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
hasilatlar.shape

(10000,)

[`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) fonksiyonunu kullanarak 4. bir sütun (column) olarak `iklim_verileri`'ne `hasilatlar`'ı ekleyelim.

In [ ]:
iklim_sonuclari = np.concatenate((iklim_verisi, hasilatlar.reshape(10000, 1)), axis=1)

In [ ]:
iklim_sonuclari

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

Burada birkaç ince nokta var:

* Yeni sütunlar (columns) eklemek istediğimiz için, `axis=1` argümanını `np.concatenate`'e aktarıyoruz. `axis` argümanı, birleştirme (concatenation) için boyutu belirtir.

* Diziler (arrays), birleştirme için kullanılan boyut dışında aynı sayıda boyuta ve her biri boyunca aynı uzunluğa sahip olmalıdır. [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) fonksiyonunu kullanarak `hasilatlar`'ın şeklini `(10000,)`'den `(10000,1)`'e değiştiririz.

İşte `axis=1` boyunca `np.concatenate`'in görsel bir açıklaması (`axis=0`ın neyle sonuçlandığını tahmin edebilir miyiz):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

Numpy fonksiyonunun ne yaptığını anlamanın en iyi yolu, onu denemek ve argümanları ve dönüş değerleri (return values) hakkında bilgi edinmek için dökümanları okumaktır. `np.concatenate` ve `np.reshape` ile denemeler yapmak için aşağıdaki hücreleri kullanalım.

Yukarıdaki hesaplamamızın sonuçlarını `np.savetxt` fonksiyonunu kullanarak bir dosyaya yazalım.

In [ ]:
iklim_sonuclari

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [ ]:
np.savetxt('iklim_sonuclari.txt', 
           iklim_sonuclari, 
           fmt='%.2f', 
           delimiter=',',
           header='sicaklik,yagis,nem,elmalarin_hasilati', 
           comments='')

Sonuçlar CSV formatında `iklim_sonuclari.txt` dosyasına yazılır.

```
sicaklik,yagis,nem,elmalarin_hasilati
25.00,76.00,99.00,72.20
39.00,65.00,70.00,59.70
59.00,45.00,77.00,65.20
84.00,63.00,38.00,56.80
...
```



Numpy, dizilerde işlem gerçekleştirmek için yüzlerce fonksiyon sağlar. İşte yaygın olarak kullanılan bazı fonksiyonlar:


* Matematik: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Dizi (array) manipülasyonu: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Lineer Cebir: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* İstatistik: `np.mean`, `np.median`, `np.std`, `np.max`

> **İhtiyacımız olan fonksiyon nasıl bulunur?** Belirli bir işlem veya kullanım durumu için doğru işlevi bulmanın en kolay yolu bir web araması yapmaktır. Örneğin, "Numpy dizilere nasıl eklenir" (how to join numpy arrays) araması, [bu eğitici, dizi (array) birleştirmeyle üzerinedir](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

Dizi (array) fonksiyonlarının tam listesini burada bulabiliriz: https://numpy.org/doc/stable/reference/routines.html

## Aritmetik işlemler, yayın (broadcasting) ve karşılaştırma

Numpy dizileri (arrays) `+`, `-`, `*` gibi aritmetik işlemleri destekler. Tek bir sayı (skaler olarak da adlandırılır) veya aynı şekle sahip başka bir dizi (array) ile aritmetik işlem gerçekleştirebiliriz. Operatörler, çok boyutlu dizilerle matematiksel ifadeler yazmayı kolaylaştırır.

In [ ]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [ ]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [ ]:
# Skaler ekleme
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [ ]:
# Öğe bazında çıkarma
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
# Skalerle bölme
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [ ]:
# Eleman bazında çarpma
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [ ]:
# Skaler ile modül
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

### Dizi Yayını (Array Broadcasting)

Numpy dizileri (arrays) aynı zamanda  farklı sayıda boyutlarda ama uyumlu şekillere sahip iki dizi arasında aritmetik işlemlere izin veren *yayınlamayı* (*broadcasting*) destekler. Nasıl çalıştığını görmek için bir örneğe bakalım.

In [ ]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr4 = np.array([4, 5, 6, 7])

In [ ]:
arr4.shape

(4,)

In [ ]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

`arr2 + arr4` ifadesi değerlendirildiğinde, `arr4` (`(4,)` şeklindedir) `arr2`'nin `(3, 4)` şekliyle eşleşmesi için üç kez çoğaltılır. Numpy, daha küçük boyutlu dizinin (array) üç kopyasını gerçekten oluşturmadan çoğaltmayı gerçekleştirir, böylece performansı artırır ve daha düşük bellek kullanır. 

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Yayın (broadcasting), yalnızca dizilerden biri diğer dizinin şekliyle eşleşecek şekilde çoğaltılabiliyorsa çalışır.

In [ ]:
arr5 = np.array([7, 8])

In [ ]:
arr5.shape

(2,)

In [ ]:
arr2 + arr5

ValueError: ignored

Yukarıdaki örnekte, `arr5` üç kez çoğaltılsa bile `arr2` şekliyle eşleşmeyecektir. Bu nedenle `arr2 + arr5` başarıyla değerlendirilemez. Buradan yayın (broadcasting) hakkında daha fazla bilgi edinebiliriz: https://numpy.org/doc/stable/user/basics.broadcasting.html .

### Dizi Karşılaştırması (Array Comparison)

Numpy dizileri ayrıca `==`, `!=`, `>` gibi karşılaştırma işlemlerini de destekler. Sonuç, bir boolean dizisidir.

In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [ ]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [ ]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

Dizi karşılaştırması, `sum` yöntemini kullanarak iki dizideki eşit öğelerin sayısını saymak için sıklıkla kullanılır. Boolean aritmetik işlemlerde kullanıldığında `True` öğesinin `1` ve `False` öğesinin `0` olarak değerlendirdiğini unutmayalım.

In [ ]:
(arr1 == arr2).sum()

3

## Array indexing and slicing

Numpy, Python'un liste indeksleme gösterimini `[]` kullanarak sezgisel bir şekilde birden çok boyuta genişletir. Numpy dizisinden belirli bir öğe veya alt dizi (dilim de denir) seçmek için virgülle ayrılmış bir indeksler veya aralıklar listesi sağlayabilirsiniz.

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],           
     [17, 18, 19.5, 43]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
# Tek eleman
arr3[1, 1, 2]

36.0

In [ ]:
# Aralıkları kullanan alt dizi
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [ ]:
# İndeksleri ve aralıkları karıştırma
arr3[1:, 1, 3]

array([18., 43.])

In [ ]:
# İndeksleri ve aralıkları karıştırma
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [ ]:
# Daha az indeks kullanma
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [ ]:
# Daha az indeks kullanma
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [ ]:
# Çok fazla indeks kullanmak
arr3[1,3,2,1]

IndexError: ignored

Gösterim ve sonuçları ilk başta kafa karıştırıcı görünebilir, bu yüzden denemek ve onunla rahat olmak için zaman ayırın. Farklı dizin ve aralık kombinasyonlarıyla bazı dizi indeksleme ve dilimleme örneklerini denemek için aşağıdaki hücreleri kullanın. İşte görsel olarak gösterilen birkaç örnek daha:

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

## Numpy dizileri oluşturmanın diğer yolları

Numpy ayrıca, sabit veya rastgele değerlerle istenen şekillerden oluşan diziler oluşturmak için bazı kullanışlı fonksiyonlar sağlar. [Resmi belgelere](https://numpy.org/doc/stable/reference/routines.array-creation.html) bakın veya daha fazla bilgi edinmek için `help` fonksiyonunu kullanın.

In [ ]:
# Hepsi sıfır
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Hepsi bir
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# Birim matris
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Rasgele vektör
np.random.rand(5)

array([0.55931288, 0.19003659, 0.95666664, 0.01144833, 0.8885526 ])

In [ ]:
# Rasgele matris
np.random.randn(2, 3) # rand vs. randn - Fark ne?

array([[-0.73613668,  0.51055154, -2.26940583],
       [-0.71777647,  1.05891478, -0.38444305]])

In [ ]:
# Sabit değer
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [ ]:
# Başlangıç, bitiş ve adım içeren aralık
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
# Bir aralıkta eşit aralıklı sayılar
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

## Gözden Geçirme Soruları

Bu notebook'da ele alınan konuları ne kadar anladığınızı test etmek için aşağıdaki soruları yanıtlamayı deneyin:

1. Vektör nedir?
2. Bir Python listesi kullanarak vektörleri nasıl temsil edersiniz? Örnek veriniz.
3. İki vektörün nokta çarpımı (dot product) nedir?
4. İki vektörün nokta çarpımını hesaplayan bir fonksiyon yazın.
5. Numpy nedir?
6. Numpy'ı nasıl yükleriz?
7. `numpy` modülünü nasıl içe aktarırız (import ederiz)?
8. Takma adı olan bir modülü içe aktarmak (import etmek) ne anlama gelir? Örnek veriniz.
9. `numpy` için kullanılan takma ad nedir?
10. Numpy dizisi nedir?
11. Numpy dizisi nasıl oluşturulur? Örnek veriniz.
12. Numpy dizilerinin türü nedir?
13. Numpy dizisinin elemanlarına nasıl erişiriz?
14. Numpy kullanarak iki vektörün nokta çarpımını (dot product) nasıl hesaplarız?
15. Farklı boyutlara sahip iki vektörün nokta çarpımını (dot product) hesaplamaya çalışırsak ne olur?
16. İki Numpy dizisinin eleman bazında çarpımını nasıl hesaplarız?
17. Bir Numpy dizisindeki tüm elemanların toplamını nasıl hesaplarız?
18. Sayısal veriler üzerinde çalışırken Python listeleri (lists) yerine Numpy dizilerini (arrays) kullanmanın faydaları nelerdir?
19. Numpy dizi işlemleri, Python fonksiyonlarına ve döngülerine (loops) kıyasla neden daha iyi performans gösteriyor?
20. Bir örnek kullanarak Numpy dizi işlemleri ile Python döngüleri arasındaki performans farkını gösterin.
21. Çok boyutlu Numpy dizileri nelerdir?
22. İki, üç ve dört boyutlu Numpy dizilerinin oluşturulmasını gösterelim.
23. Bir Numpy dizisindeki boyutların sayısını ve her bir boyut boyunca uzunluğu nasıl inceleriz?
24. Numpy dizisinin elemanları farklı veri tiplerine sahip olabilir mi?
25. Numpy dizisinin elemanlarının veri türünü nasıl kontrol ederiz?
26. Numpy dizisinin veri türü nedir?
27. Bir matris ve bir 2 boyutlu Numpy dizisi arasındaki fark nedir?
28. Numpy kullanarak matris çarpımını nasıl gerçekleştiririz?
29. Numpy'da kullanılan `@` operatörü nedir?
30. CSV dosya formatı nedir?
31. Numpy kullanarak bir CSV dosyasındaki verileri nasıl okuruz?
32. İki Numpy dizisini (arrays) nasıl birleştiririz?
33. `np.concatenate`'in `axis` argümanının amacı nedir?
34. Birleştirme için iki Numpy dizisi ne zaman uyumludur?
35. Birleştirilebilen iki Numpy dizisine bir örnek verelim.
36. Birleştirilemeyen iki Numpy dizisine bir örnek verelim.
37. `np.reshape` fonksiyonunun amacı nedir?
38. Bir Numpy dizisini “yeniden şekillendirmek” (reshape) ne anlama gelir?
39. Bir CSV dosyasına numpy dizisini nasıl yazarız?
40. Matematiksel işlemleri gerçekleştirmek için Numpy fonksiyonlarına bazı örnekler verelim.
41. Dizi manipülasyonu yapmak için Numpy fonksiyonlarına bazı örnekler verelim.
42. Lineer cebir gerçekleştirmek için Numpy fonksiyonlarına bazı örnekler verelim.
43. İstatistiksel işlemleri gerçekleştirmek için Numpy fonksiyonlarına bazı örnekler verelim.
44. Belirli bir işlem veya kullanım durumu için doğru Numpy fonksiyonunu nasıl buluruz?
45. Tüm Numpy dizisi fonksiyonlarının ve işlemlerinin listesini nerede görebiliriz?
46. Numpy dizileri tarafından desteklenen aritmetik işlemler nelerdir? Örneklerle anlatalım.
47. Dizi yayını (array broadcasting) nedir? Nasıl faydalıdır? Bir örnekle açıklayalım.
48. Yayına (broadcasting) uygun dizilere birkaç örnek verelim.
49. Yayına (broadcasting) uygun olmayan dizilere bazı örnekler verelim.
50. Numpy dizileri tarafından desteklenen karşılaştırma işlemleri nelerdir? Örneklerle anlatalım.
51. Bir Numpy dizisinden belirli bir alt diziye veya dilime nasıl erişiriz?
52. Çok boyutlu Numpy dizilerinde dizi indeksleme (array indexing) ve dilimlemeyi (slicing) bazı örneklerle gösterelim.
53. Tamamen 0'lar içeren belirli bir şekle sahip Numpy dizisini nasıl oluştururuz?
54. Tamamen 1'ler içeren belirli bir şekle sahip bir Numpy dizisini nasıl oluştururuz?
55. Belirli bir şekle sahip birim matris nasıl oluştururuz?
56. Belirli bir uzunlukta olan rastgele bir vektörü nasıl oluştururuz?
57. Her eleman için sabit bir değere sahip belirli bir şekilde olan Numpy dizisini nasıl oluştururuz?
58. Rastgele başlatılmış elemanlar içeren belirli bir şekle sahip bir Numpy dizisini nasıl oluştururuz?
59. `np.random.rand` ile `np.random.randn` arasındaki fark nedir? Örneklerle anlatalım.
60. `np.arange` ile `np.linspace` arasındaki fark nedir? Örneklerle anlatalım.
